spring.application.name=FIXORA

spring.datasource.url=jdbc:mysql://localhost:3306/fixoraDB
spring.datasource.username=root
spring.datasource.password=gojo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=6996